### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by JanneKiiskila** [iconservo/wifi-winc1500#19]
This repository does not have an explicit license, please add one to prevent any unclarities with licensing.

**Comment by ChiefBureaucraticOfficer** [comment]
Hi @kannanputhuval ,
Files within this repository have originated within the Mbed OS project and were originally marked with the Apache License.  Could you update the repository license to Apache or similar permissive open source license?  MIT or BSD would also be adequate.

For the files originated from Arm's Mbed OS project please re-apply the original Apache licenses.

Regards,
Aaron Morris
