### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by ChiefBureaucraticOfficer** [iconservo/wifi-winc1500#21]
Hi @kannanputhuval ,
Files within this repository have originated within the Mbed OS project and were originally marked with the Apache License. Could you update the repository license to Apache or similar permissive open source license? MIT or BSD would also be adequate.

For the files originated from Arm's Mbed OS project please re-apply the original Apache licenses.

Regards,
Aaron Morris

**Comment by kannanputhuval** [comment]
@ChiefBureaucraticOfficer thanks for pointing this out. I've created a PR to change to the Apache License 2.0.

> For the files originated from Arm's Mbed OS project please re-apply the original Apache licenses.

Are you reiterating for clarity, or does this mean something in addition to the first request?

**Comment by JanneKiiskila** [comment]
Having one Apache 2.0 license covers everything.
