### ISSUE TITLE
Firmware upgrade functionality - WINC1500

### ISSUE THREAD

**Issue by kaidokert** [iconservo/wifi-winc1500#9]
Host MCU needs to be able to upload a new image into OTA region on WINC15. Also certs

**Comment by nkryciklum** [comment]
@dmBadekha please, have a look at this.

**Comment by nkryciklum** [comment]
discuss risks of firmware update via spi and alternative of OTA update instead.

**Comment by nkryciklum** [comment]
make experimental branch - delete softdevice and implement upgrade of winc image and validate it works

**Comment by dmBadekha** [comment]
Two branches are created in different repos:
https://github.com/iconservo/mbed-smartvalve-firmware/tree/dbad.dev-winc1500-upgrade-issue9;
https://github.com/iconservo/wifi-winc1500/tree/dbad.dev-winc-upgrade-func-issue9.
This solution have to be checked on new platform.

**Comment by nkryciklum** [comment]
Check on mockup board

**Comment by dmBadekha** [comment]
@kaidokert is SSL certificates write to WINC chip necessary for now? I can write any data to any region of WINC flash, but I can't pack certificates to binary. In original utility this operation is performed by separate exe file.

**Comment by yeka-ciklum** [comment]
As was discussed yesterday on scrum meeting we can skip for now  SSL certificates write to WINC feature.

**Comment by dmBadekha** [comment]
Firmware upgrade functionality - WINC1500

For check direct flash write of WINC1500 chip read/write functions were implemented. Some auxiliary functions were implemented too.
Source .bin file is converted to const char array in appropriate header file.
Function calls implemented as cli commands in group "winc_flash". Work commands for "winc_flash" group:
* version - displays version of active and OTA partitions;
* mode_on - switch SPI flash firmware download mode. This command have to be performed before other manipulations with WINC flash;
* read <addr bytes> - read number of "bytes" (max value 32) from "addr" address in WINC flash;
* write_chip - rewrite of whole WINC chip;
* chip_erase - erase whole chip.

All code posted in 2 branches:
https://github.com/iconservo/wifi-winc1500/tree/dbad.dev-winc-upgrade-func-issue9
https://github.com/iconservo/mbed-smartvalve-firmware/tree/dbad.dev-winc1500-upgrade-issue9

**Comment by kaidokert** [comment]
@dmBadekha can you PR the wici-winc1500 repo please ?

**Comment by sktatyana** [comment]
Issues from https://github.com/iconservo/mbed-smartvalve-firmware/issues/244 should be reviewed and fixed where possible prior to ticket closing

**Comment by sktatyana** [comment]
Functionality was checked in dbad.dev-winc1500-upgrade-issue9 branch. 
All commands need started wifi module before executing (`wifi_start`). Checked:
* `winc_flash version` that prints out version of active and OTA partitions
* `winc_flash mode_on` that switches SPI  flash to download mode. All command below won't work without entering download mode 
* `winc_flash read <address>` need address in hex format
* `winc_flash write_chip` writes (over existing or absent) WINC chip
* `winc_flash chip_erase` erases WINC from the board. FW then works fine but wifi commands do not work without it
